import { NextResponse, type NextRequest } from 'next/server';
import { renderToStream } from '@react-pdf/renderer';
import { getCurrentBusiness } from '@/lib/business';
import { getReportData } from '@/lib/queries/reports';
import { getExportDetail } from '@/lib/queries/export-detail';
import {
  parseRangeKey,
  resolveDateRange,
  monthToDateRange,
  parseMonth,
} from '@/lib/date-range';
import { formatEGP } from '@/lib/money';
import { buildPdfDocument } from '@/components/reports/pdf-document';

export const runtime = 'nodejs';

const RANGE_LABELS: Record<string, { en: string; ar: string }> = {
  'this-month': { en: 'This month', ar: 'هذا الشهر' },
  'last-month': { en: 'Last month', ar: 'الشهر الماضي' },
  'this-year': { en: 'This year', ar: 'هذه السنة' },
  'all-time': { en: 'All time', ar: 'كل الأوقات' },
};

const STRINGS = {
  en: {
    totalIn: 'Total in',
    totalOut: 'Total out',
    profit: 'Profit',
    topChannels: 'Top revenue channels',
    topCategories: 'Top expense categories',
    momTitle: 'Versus last period',
    momMetricRevenue: 'Revenue',
    momMetricExpenses: 'Expenses',
    momMetricProfit: 'Profit',
    momCurrentHeader: 'Current',
    momPreviousHeader: 'Previous',
    momChangeHeader: 'Change',
    unpaidTitle: 'Unpaid summary',
    unpaidRevenueLabel: 'Unpaid revenue',
    unpaidExpensesLabel: 'Unpaid expenses',
    countWord: 'entries',
    revenueDetailTitle: 'Revenue entries',
    expenseDetailTitle: 'Expense entries',
    dateHeader: 'Date',
    nameHeader: 'Name',
    counterpartyHeader: 'Channel / Vendor',
    paymentHeader: 'Payment',
    statusHeader: 'Status',
    shopifyTitle: 'Shopify',
    collectionRateLabel: 'Collection rate',
    revenueGapLabel: 'Revenue gap',
    orderVolumeLabel: 'Order volume',
    totalOrderedLabel: 'Total ordered',
    avgOrderValueLabel: 'Avg order value',
    refundedLabel: 'Refunded',
    shopifyOrdersTitle: 'Recent Shopify orders',
    orderHeader: 'Order',
    customerHeader: 'Customer',
    uncategorized: 'Uncategorized',
    noData: 'No data for this period.',
    channelHeader: 'Channel',
    categoryHeader: 'Category',
    amountHeader: 'Amount',
    shareHeader: 'Share',
    countHeader: 'Count',
    generatedOn: 'Generated',
    footer: 'Generated by Hesabaty Business — hesabaty.com',
    paid: 'Paid',
    unpaid: 'Unpaid',
  },
  ar: {
    totalIn: 'إجمالي الإيرادات',
    totalOut: 'إجمالي المصروفات',
    profit: 'صافي الربح',
    topChannels: 'أكثر قنوات البيع',
    topCategories: 'أكثر تصنيفات المصروفات',
    momTitle: 'مقارنة بالفترة السابقة',
    momMetricRevenue: 'الإيرادات',
    momMetricExpenses: 'المصروفات',
    momMetricProfit: 'الربح',
    momCurrentHeader: 'الحالي',
    momPreviousHeader: 'السابق',
    momChangeHeader: 'التغير',
    unpaidTitle: 'ملخص غير المحصّل',
    unpaidRevenueLabel: 'إيرادات غير محصّلة',
    unpaidExpensesLabel: 'مصروفات غير مدفوعة',
    countWord: 'عملية',
    revenueDetailTitle: 'تفاصيل الإيرادات',
    expenseDetailTitle: 'تفاصيل المصروفات',
    dateHeader: 'التاريخ',
    nameHeader: 'الاسم',
    counterpartyHeader: 'القناة / المورد',
    paymentHeader: 'طريقة الدفع',
    statusHeader: 'الحالة',
    shopifyTitle: 'شوبيفاي',
    collectionRateLabel: 'نسبة التحصيل',
    revenueGapLabel: 'الفجوة في الإيراد',
    orderVolumeLabel: 'عدد الطلبات',
    totalOrderedLabel: 'إجمالي الطلبات',
    avgOrderValueLabel: 'متوسط قيمة الطلب',
    refundedLabel: 'مرتجعة',
    shopifyOrdersTitle: 'آخر طلبات شوبيفاي',
    orderHeader: 'الطلب',
    customerHeader: 'العميل',
    uncategorized: 'بدون تصنيف',
    noData: 'لا توجد بيانات لهذه الفترة.',
    channelHeader: 'القناة',
    categoryHeader: 'التصنيف',
    amountHeader: 'المبلغ',
    shareHeader: 'النسبة',
    countHeader: 'العدد',
    generatedOn: 'تم الإنشاء',
    footer: 'مُنشأ بواسطة حسباتي بزنس — hesabaty.com',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
  },
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ locale: string }> },
) {
  const { locale: rawLocale } = await params;
  const locale: 'en' | 'ar' = rawLocale === 'ar' ? 'ar' : 'en';

  const business = await getCurrentBusiness();
  if (!business) return new NextResponse('Unauthorized', { status: 401 });

  const monthParam = request.nextUrl.searchParams.get('month');
  const monthRange = monthToDateRange(monthParam);
  const rangeKey = parseRangeKey(request.nextUrl.searchParams.get('range'));
  const range = monthRange
    ? {
        key: 'this-month' as const,
        startISO: monthRange.startISO,
        endISO: monthRange.endISO,
      }
    : resolveDateRange(rangeKey);

  const [data, detail] = await Promise.all([
    getReportData(business.id, range),
    getExportDetail(business.id, range),
  ]);

  const strings = STRINGS[locale];
  const periodLabel = parseMonth(monthParam)
    ? String(monthParam)
    : RANGE_LABELS[rangeKey]?.[locale] ?? '';

  const doc = await buildPdfDocument({
    data,
    detail,
    locale,
    strings: {
      ...strings,
      businessName: business.name,
      periodLabel,
      generatedOn: `${strings.generatedOn} ${new Date().toISOString().slice(0, 10)}`,
    },
    format: (n: number) => formatEGP(n, locale === 'ar' ? 'ar' : 'en'),
  });

  const stream = await renderToStream(doc);
  const chunks: Buffer[] = [];
  for await (const chunk of stream as unknown as AsyncIterable<Buffer | string>) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }
  const buffer = Buffer.concat(chunks);

  const filenameKey = parseMonth(monthParam) ? String(monthParam) : rangeKey;
  const filename = `hesabaty-${filenameKey}-${new Date().toISOString().slice(0, 10)}.pdf`;
  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  });
}
